<div class="container tabela">
    <table class="table ">
        <thead class="thead-dark">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Primeiro Nome</th>
                <th scope="col">Último Nome</th>
                <th scope="col">UF</th>
                <th scope="col">Cidade</th>
                <th scope="col">Email</th>
                <th colspan="2">Operações</th>
            </tr>
        </thead>'