<main class="bd-masthead texto_inicial" id="content" role="main">
    <div class="container">
        <div class="row">
            <div class="col-6 mx-auto col-md-4 order-md-2">
                <img src="img/logo.jpeg" width="512" height="475" class="img-fluid mb-3 mb-md-0" viewBox="0 0 1024 860" focusable="false" role="img"></img>
            </div>
            <div class="col-md-8 order-md-1 text-center text-md-left pr-md-5">
                <h1 class="mb-3">EcoMoney, administre suas finanças</h1>
                <p class="lead mb-4">
                    Aqui você pode inserir seus ganhos e gastos e então encontrar a melhor maneira para economizar. Torne-se um empreendedor, poupe agora e colha os lucros no futuro.
                </p>
            </div>
        </div>
    </div>
</main>
